### ISSUE TITLE
사진이 깨져요

### ISSUE THREAD

**Issue by Goolgae** [sunrabbit123/TIL#1]
@sunrabbit123 사진이 깨지는것 같은데요.. 🧐

[**문제의 부분**](https://github.com/sunrabbit123/TIL/blob/main/Security/eledronic_signature.md)

![2021-02-07_23-54-05](https://user-images.githubusercontent.com/60869316/107150218-2288b300-69a0-11eb-9da1-f8cae08af695.png)

링킹 잘못하셨나?

**Comment by sunrabbit123** [comment]
슬프네요 :(
수정하도록하겠습니다.

**Comment by Goolgae** [comment]
넼ㅋㅋㅋ

**Comment by sunrabbit123** [comment]
링킹을 시도할때 디렉터리 이름을 소문자로 써서 생긴 에러였다고합니다.
수정완료했습니다
