### ISSUE TITLE
markdown이 깨진거같아요

### ISSUE THREAD

**Issue by siwony** [sunrabbit123/TIL#2]
[https://github.com/sunrabbit123/TIL/blob/main/Web/browser.md](https://github.com/sunrabbit123/TIL/blob/main/Web/browser.md) 여기에 이미지랑 텍스트랑 겹친거같아요

**Comment by siwony** [comment]
![스크린샷 2021-02-08 19 49 32](https://user-images.githubusercontent.com/62932968/107209950-d775ab00-6a46-11eb-985c-99c6e9f8b2a0.png)

**Comment by Goolgae** [comment]
제목이 깨진것 같아요 #2

> markdwon -> markdown

**Comment by sunrabbit123** [comment]
아 줄바꿈ㅇ..... 제보 감사합니ㅏㄷ.
